{% set name = "ligo-gracedb" %}
{% set version = "2.5.0" %}
{% set sha256 = "d632f9ec5a04e2b954e9a16d97a5041567ab0e75026ef48ea5bda56f5ff00bc7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - gracedb = ligo.gracedb.cli.client:main
    - gracedb_legacy = ligo.gracedb.legacy_cli:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - cryptography >=1.7.2
    - future >=0.15.0
    - ligo-common
    - python
    - six >=1.10.0

test:
  imports:
    - ligo.gracedb.rest
  commands:
    - gracedb --help
    - gracedb_legacy --help

about:
  home: https://wiki.ligo.org/Computing/DASWG/GraceDB
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Gravitational Wave Candidate Event Database
  description: |
    The gravitational-wave candidate event database (GraceDB) is a prototype
    system to organize candidate events from gravitational-wave searches and
    to provide an environment to record information about follow-ups. A simple
    client tool is provided to submit a candidate event to the database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - tprestegard
