{% set name = "ligo-gracedb" %}
{% set version = "2.2.0" %}
{% set sha256 = "67a4a43fb82f092ed8a8ec20824f7451c63194c168730ada14f64df123019699" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Only-install-setup_requires-requirements-for-the-spe.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - gracedb = ligo.gracedb.cli:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - future
    - ligo-common

test:
  imports:
    - ligo.gracedb.rest
  commands:
    - gracedb --help

about:
  home: https://wiki.ligo.org/Computing/DASWG/GraceDB
  license: GPL
  license_family: GPL
  license_file: COPYING
  summary: Gravitational Wave Candidate Event Database
  description: |
    The gravitational-wave candidate event database (GraceDB) is a prototype
    system to organize candidate events from gravitational-wave searches and
    to provide an environment to record information about follow-ups. A simple
    client tool is provided to submit a candidate event to the database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - tprestegard
