{% set name = "ligo-gracedb" %}
{% set version = "2.7.1" %}
{% set sha256 = "f4e481c86426b34d1128323914aa0ca58b4e49300bf583d6ea8f882ad40a1eed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gracedb = ligo.gracedb.cli.client:main
    - gracedb_legacy = ligo.gracedb.legacy_cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - cryptography >=1.7.2
    - future >=0.15.0
    - ligo-common
    - python
    - requests >=2.6.0
    - six >=1.9.0

test:
  imports:
    - ligo.gracedb.rest
  requires:
    - pytest
  commands:
    # basic test
    - gracedb --help
    - gracedb_legacy --help
    # run actual query against database (but don't fail just incase service isn't available)
    - gracedb search superevents "far<1e-9" --columns superevent_id,far,labels --force-noauth || true
    # run test suite (without integration tests, which require network)
    - python -m pytest --pyargs ligo.gracedb -m "not integration"

about:
  home: https://ligo-gracedb.readthedocs.io/
  doc_url: https://ligo-gracedb.readthedocs.io/
  dev_url: https://git.ligo.org/lscsoft/gracedb-client
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A Python package for accessing the GraceDB API
  description: |
    The Gravitational-wave Candidate Event Database (GraceDB) is a
    web service designed for aggregating and communicating information
    about candidate events from gravitational-wave searches and
    associated follow-ups.  `ligo-gracedb` provides a Python-based
    client tool for facilitating interactions with the GraceDB API.

extra:
  recipe-maintainers:
    - aepace
    - duncanmmacleod
