{% set name = "ligo-gracedb" %}
{% set version = "2.2.1" %}
{% set sha256 = "68a537596320650c8c846d55cfb1197093398cbf184759a16a657de9869f29b8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - default_server.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - gracedb = ligo.gracedb.cli.client:main
    - gracedb_legacy = ligo.gracedb.legacy_cli:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six >=1.10.0
    - future >=0.15.0
    - ligo-common

test:
  imports:
    - ligo.gracedb.rest
  commands:
    - gracedb --help
    - gracedb_legacy --help

about:
  home: https://wiki.ligo.org/Computing/DASWG/GraceDB
  license: GPL
  license_family: GPL
  license_file: COPYING
  summary: Gravitational Wave Candidate Event Database
  description: |
    The gravitational-wave candidate event database (GraceDB) is a prototype
    system to organize candidate events from gravitational-wave searches and
    to provide an environment to record information about follow-ups. A simple
    client tool is provided to submit a candidate event to the database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - tprestegard
