{% set name = "ligo-gracedb" %}
{% set version = "2.1.1" %}
{% set sha256 = "89af02c3d9bba0971168de14daa1a706f5aed4515c744111a3c51aa9ea5ebb8b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - gracedb = ligo.gracedb.cli:main

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six
    - future
    - ligo-common

test:
  requires:
    - pytest
  imports:
    - ligo.gracedb.rest
  commands:
    - gracedb --help

about:
  home: https://wiki.ligo.org/DASWG/GraceDB
  license: GPL
  license_family: GPL
  summary: Gravitational Wave Candidate Event Database
  description: |
    The gravitational-wave candidate event database (GraceDB) is a prototype
    system to organize candidate events from gravitational-wave searches and
    to provide an environment to record information about follow-ups. A simple
    client tool is provided to submit a candidate event to the database.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - tprestegard
