travis:
  secure:
    BINSTAR_TOKEN: WbrR+UlEiBfvtiK3TnHSIih5J37l0DdRyKedz36XkKTpUI045iAhbBPHwIdq/Npi7tIo+IQVCRqHFgHVRlSSlD6282VGrTWOZbbpX6ALogrFyeS921tf1vgCjMjSXSzDOG9yqG+W1FBLaVDijLmOpgiV4D8WT7TSKMJ4O/jv5tHMqPoJEpkJW05v1Oozr8SCuQbUhSetl6qJW2ppHQh53WSd6CIQRQt1ku8Dp86leEaABid8cU+G+eZ/VKyaE5ZoFzxKaA+uonh8h0L+Oo0zQm0PbA4Rlpe8pfRzFoDlLaq7oazEP06HU5urOzEikLQRWwMdU+I99mJKfVC8jDRLasTEhxd1b/EWUgu16yrwC3wBo8neeFYGIVbTm4siDT+OOqUkXexpueNNH2NQ2HTnlceVZDbyzmj3CUWyc2tTPqtfcOnTMWH0bZ3aXH+GHT7k0HfM2kJceQCLmvikge6ouMTYOisi86NrvpguOTdywjWt9w/RDhJ+H0KjIywsgc/EKAXM1OpQoCsoBdZo/qo8kV9ULx4aDivLOq5tOJoaGu/o9IpQl1b4/ZcPbM0Io2aKnXjIWB1RXMu5bahlnsFKZHLzpUi1HH/KMPxJ/FtGQEIBOUKzc0p710RYaBeyZbyqnw46zwvWzgIHxhVunpG9Ty7oJfNZysNOvdXq6y4hStw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
